### ISSUE TITLE
AssetBundleSchema should implement FileRepositoryLoader

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/assets#3]
`AssetBundleSchema` loads the asset bundle schema files and merges them together.

This should probably be an implementation of `UserFrosting/Support/Repository/Loader/FileRepositoryLoader`.

**Comment by Silic0nS0ldier** [comment]
Just in case someone is following this issue, this library is currently undergoing a major rewrite that will make it much more compatible with various frontend asset bundling systems. These changes are large enough that this issue will likely not apply to the next major release.

**Comment by Silic0nS0ldier** [comment]
The loader is better used internally (and will help to address some downstream problems). Doing this to support `Repository` simply doesn't offer enough gain for the increased overhead that making it the preferred option would bring.

**Comment by Silic0nS0ldier** [comment]
Described changes are now implemented in develop
